# Generated by Django 4.1.9 on 2023-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commands_syntax", models.CharField(max_length=60)),
                ("is_Admin", models.BooleanField()),
                ("description", models.CharField(max_length=120)),
            ],
        ),
    ]
